"""empty message

Revision ID: 002e16a2e5d5
Revises: 2aadec0f51ff
Create Date: 2023-01-18 18:41:46.541060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002e16a2e5d5'
down_revision = '2aadec0f51ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.create_unique_constraint("email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
